config/routes.rb
Rails.application.routes.draw do

  get 'pages/show'

  get 'orders/new'

  get 'addresses/new'

  get 'address/new'

  get 'charges/new'

  get 'charges/create'

  resources :products, only: [:index, :show] do

    member do
      post :add_to_cart
    end
  end

  resources :charges, only: [:new, :create]
  resources :address, only: [:new]
  resources :orders, only: [:new]
  resources :categories, only: [:index]

  post 'address/add_to_db'
  root to: 'products#index'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :user
  belongs_to :province

  validates :address_name, :postal_code, :city, :userid, :provinceid, presence: true
  validates :postal_code, format:
      { with: /\A[ABCEGHJKLMNPRSTVXY]{1}\\d{1}[A-Z]{1}[ -]?\\d{1}[A-Z]{1}\\d{1}\z/ }
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :email, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products, dependent: :destroy

  validates :category_name, presence: true

  def name
    category_name
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :ordered_products, dependent: :destroy
  has_many :products, through: :ordered_products

  validates :total, :userId, presence: true
end

app/models/ordered_product.rb
class OrderedProduct < ApplicationRecord
end

app/models/page.rb
class Page < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  # has_many :ordered_products
  # has_many :orders, through: :ordered_products, dependent: :destroy
  # accepts_nested_attributes_for :category, allow_destroy: true

  validates :name, :description, :price, :quantity, :category_id, presence: true

  mount_uploader :image, ImageUploader

  def self.search(search)
    @product = if search
                 Product.where('name LIKE :search OR description LIKE :search',
                               search: "%#{search}%")
               else
                 Product.all
               end
  end
end

app/models/province.rb
class Province < ApplicationRecord
  has_many :addresses, dependent: :destroy

  validates :name, :gst, :pst, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # include Clearance::User

  has_many :addresses, dependent: :destroy
  has_many :orders, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # include Clearance::Controller
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.where.not(id: 8)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def show
    @page = Page.find(params[:page])
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :initialize_session
  before_action :load_shopping_cart

  def index
    load_by_category_search

    load_by_filter if params.key?(:filter)

    load_by_category
  end

  def show
    @product = Product.find(params[:id])
  end

  def add_to_cart
    id = params[:id].to_i

    session[:cart_items] << id unless session[:cart_items].include?(id)
    redirect_to products_path
  end

  def load_shopping_cart
    @cart_items = Product.find(session[:cart_items])
  end

  private

  def initialize_session
    session[:cart_items] ||= []
    session[:user] = User.first.id
  end

  def load_by_category
    @products = category_index if params.key?(:category_index)
  end

  def load_by_filter
    @products = if params[:filter] == 'sale'
                  @products.where(on_sale: true)
                else
                  @products.where('created_at > ?', 7.days.ago)
                end
  end

  def load_by_category_search
    @products = if !params.key?(:category_id) || params[:category_id] == '8'
                  none_category
                else
                  some_category
                end
  end

  def none_category
    Product.search(params[:search]).page(params[:page]).per(5)
  end

  def some_category
    Product.where(category_id: params[:category_id])
           .search(params[:search])
           .page(params[:page]).per(5)
  end

  def category_index
    Product.where(category_id: params[:category_index])
           .order(:name).page(params[:page]).per(5)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/categories/index.html.erb
<h1>Categories</h1>
<ul class="list-group">
  <% @categories.each do |category| %>
    <li class="list-group-item"><%= link_to category.category_name, products_path(category_index: category.id) %></li>
  <% end %>
</ul>

app/views/layouts/_navigation.html.erb
<div class="container">
  <Header>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <%= link_to 'Curtis Sporting Goods', root_path, class: "navbar-brand" %>
        <ul class="navbar-nav mr-auto">
          <li class="nav-item"><%= link_to 'Home', root_path, class: "nav-link" %></li>
          <li class="nav-item"><%= link_to 'About', pages_show_path(page: 1), class: "nav-link" %></li>
          <li class="nav-item"><%= link_to 'Contact', pages_show_path(page: 2), class: "nav-link" %></li>
          <li class="nav-item"><%= link_to 'Categories', categories_path, class: "nav-link" %></li>
          <% if current_page?(products_path) or current_page?(root_path) %>
            <%= form_tag(products_path, method: :get, class: "form-inline my-2 my-lg-0") do %>
              <%= select_tag "category_id", options_from_collection_for_select(Category.all, "id", "category_name", "8"),
                             style: 'padding: 5px; margin-right: 20px; margin-left: 75px' %>
              <%= text_field_tag :search, params[:search], class: "form-control mr-sm-2" %>
              <%= submit_tag 'Search', name: nil, class: "btn btn-outline-success my-2 my-sm-0" %>
            <% end %>
          <% end %>
        </ul>
      </div>
    </nav>
  </Header>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CurtisSportingGoods</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <%= yield %>
  </body>
</html>

app/views/pages/show.html.erb
<h1><%= @page.title %></h1>
<p><%= @page.body.html_safe %></p>

app/views/product/_product.html.erb
<h2><%= product.name %> </h2>
<p><%= image_tag(product.image) %></p>
<p> $<%= product.price %> </p>
<p> qty: <%= product.quantity %> </p>

app/views/product/index.html.erb
<%= render @products %>

app/views/products/_product.html.erb
<div class="card" style="width: 30rem;">
  <div class="card-body">
    <h5 class="card-title"><%= link_to product.name, product_path(product) %></h5>

    <% if product.image.present? %>
      <p><%= image_tag product.image, width: 150, height: 150 %></p>
    <% end %>

    <p class="card-text"> <strong>Price: $</strong><%= product.price %> </p>
    <p class="card-text"> <strong>Qty: </strong><%= product.quantity %> </p>
    <p class="card-text"> <strong>Date added: </strong><%= product.created_at.to_s[0..10] %></p>
    <% if product.on_sale %>
      <p class="card-text">On sale!</p>
    <% end %>
    <%= button_to "Add to Cart", add_to_cart_product_path(product) %>
  </div>
</div>

app/views/products/index.html.erb
<div>
  <h2>Shopping Cart</h2>
  <% @cart_items.each do |cart_item|  %>
    <%= cart_item.name %>: $ <%= cart_item.price %><br>
  <% end %>
</div><br>

<div>
  <p>Sort by:</p>
  <ul class="list-group">
    <li class="list-group-item"><%= link_to "On sale", products_path(filter: 'sale')%></li>
    <li class="list-group-item"><%= link_to "Date added", products_path(filter: 'new')%></li>
  </ul>
</div>

<div class="card-group">
  <%= render @products %>
</div>

<%= paginate @products %>

app/views/products/show.html.erb
<div class="container">
  <div class="card" style="width: 30rem;">
    <div class="card-body">
      <h2 class="card-title"><%= @product.name %></h2>
      <% if @product.image.present? %>
        <p ><%= image_tag @product.image %></p>
      <% end %>
      <p class="card-text"><%= @product.description %></p>
      <p class="card-text"><strong>Price: $</strong><%= @product.price %></p>
      <p class="card-text"><strong>Qty: </strong><%= @product.quantity %></p>
      <% if @product.on_sale %>
        <p class="card-text">On sale!</p>
      <% end %>
    </div>
  </div>
</div>